import "./globals.css";
import { Inter, Lalezar } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className={lalezar.className}>أحمد سامي</h1>
        <nav>
          <ul>
            <li>About</li>
            <li>Blog</li>
            <li>Portfolio</li>
            <li>Contact</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
